# Generated by Django 5.2 on 2025-11-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('home', '0013_alter_componente_curricular_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='turma',
            field=models.ForeignKey(default=0.0005, on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
            preserve_default=False,
        ),
    ]
