# Generated by Django 5.2 on 2025-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_grade_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira')], default=1, max_length=20, verbose_name='Dia Semana'),
            preserve_default=False,
        ),
    ]
