# Generated by Django 5.2 on 2025-05-25 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=200)),
                ('num', models.IntegerField(verbose_name='Num')),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=200)),
                ('mora_com_quem', models.CharField(choices=[('avós', 'avós'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=200, verbose_name='Mora com quem?')),
                ('tem_irmaos', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=3, verbose_name='Tem irmãos?')),
                ('prob_saude', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='prob saúde')),
                ('medic_continuo', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='Medic continuo?')),
                ('medic_qual', models.CharField(max_length=200, verbose_name='Medic qual?')),
                ('tem_alergias', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=200, verbose_name='tem_alergias?')),
                ('aler_qual', models.CharField(max_length=200, verbose_name='aler_qual?')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('profissao', models.CharField(max_length=200, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Registro_Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cafe', models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Café')),
                ('alm', models.CharField(blank=True, choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, null=True, verbose_name='Almoço')),
                ('col', models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Colação')),
                ('jnt', models.CharField(choices=[('nada', 'nada'), ('pouco', 'pouco'), ('tudo', 'tudo')], max_length=100, verbose_name='Janta')),
                ('ev_L', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ev.Liquida')),
                ('ev_P', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ev.Pastosa')),
                ('bnh', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=100, verbose_name='Banho')),
                ('sono', models.CharField(choices=[('tranquilo', 'tranquilo'), ('agitado', 'agitado'), ('não dormiu', 'não dormiu')], max_length=100)),
                ('obs', models.TextField(max_length=25, verbose_name='observações')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='home.crianca', verbose_name='Criança')),
                ('cuidador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='home.cuidador')),
            ],
            options={
                'verbose_name': 'Registro Diário',
                'verbose_name_plural': 'Registro Diário',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=200, verbose_name='Profissão')),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AddField(
            model_name='crianca',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, to='home.responsavel'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sala'),
        ),
    ]
