# Generated by Django 5.2 on 2025-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_componente_curricular_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente_curricular',
            options={'verbose_name': 'Componente_Curricular', 'verbose_name_plural': 'Componente_Curricular'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AddField(
            model_name='professor',
            name='componente_curricular',
            field=models.TextField(default='DDD', verbose_name='Componente Curricular'),
            preserve_default=False,
        ),
    ]
