# Generated by Django 5.2 on 2025-11-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_componente_curricular_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='componente_curricular',
        ),
    ]
