# Generated by Django 5.2 on 2025-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_professor_componente_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='componente_curricular',
            field=models.TextField(default='dd', max_length=25, verbose_name='Componente Curricular'),
            preserve_default=False,
        ),
    ]
