# Generated by Django 5.2 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_professor_componente_curricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='componente_curricular',
            field=models.TextField(max_length=500, verbose_name='Componente Curricular'),
        ),
    ]
