# Generated by Django 5.2 on 2025-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_professor_componente_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='substituto',
            field=models.BooleanField(default=False),
        ),
    ]
