# Generated by Django 5.2 on 2025-11-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_justificativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmento',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.justificativa')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turma',
            },
        ),
    ]
