# Generated by Django 5.2 on 2025-11-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_segmento_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.segmento'),
        ),
    ]
