# Generated by Django 5.2 on 2025-11-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.periodo'),
            preserve_default=False,
        ),
    ]
