# Generated by Django 5.2 on 2025-11-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_turma_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente_curricular',
            options={'verbose_name': 'Componente Curricular', 'verbose_name_plural': 'Componente Curricular'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Período', 'verbose_name_plural': 'Período'},
        ),
    ]
