# Generated by Django 5.2 on 2025-11-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_Ausente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sala',
            },
        ),
    ]
