# Generated by Django 5.2 on 2025-11-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor_ausente',
            options={'verbose_name': 'Professor Ausente', 'verbose_name_plural': 'Professor Ausente'},
        ),
    ]
