# Generated by Django 5.2 on 2025-11-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_professor_componente_curricular'),
        ('ocorrencia', '0002_alter_professor_ausente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_ausente',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.professor'),
            preserve_default=False,
        ),
    ]
