# Generated by Django 5.2 on 2025-11-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_justificativa'),
        ('ocorrencia', '0003_professor_ausente_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_ausente',
            name='justificativa',
            field=models.ForeignKey(default=0.0004950495049504951, on_delete=django.db.models.deletion.CASCADE, to='home.justificativa'),
            preserve_default=False,
        ),
    ]
