# Generated by Django 5.2 on 2025-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_professor_ausente_justificativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_ausente',
            old_name='data',
            new_name='inicio',
        ),
        migrations.AddField(
            model_name='professor_ausente',
            name='fim',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
