# Generated by Django 5.2 on 2025-11-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_componente_curricular_options_and_more'),
        ('ocorrencia', '0005_rename_data_professor_ausente_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_Substituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ausente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
            ],
            options={
                'verbose_name': 'Professor Substituto',
                'verbose_name_plural': 'Professor Substituto',
            },
        ),
    ]
