# Generated by Django 5.2 on 2025-11-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_componente_curricular_options_and_more'),
        ('ocorrencia', '0006_professor_substituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_substituto',
            name='substituto',
            field=models.ForeignKey(default=0.0004950495049504951, on_delete=django.db.models.deletion.CASCADE, related_name='Professor_Substituto', to='home.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor_substituto',
            name='ausente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professor_Ausente', to='home.professor'),
        ),
    ]
