# Generated by Django 5.2 on 2025-05-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunicacao', 'Comunicação'), ('evento', 'Evento'), ('observacao', 'Observação'), ('pedagogicos', 'Pedagógicos')], max_length=20, verbose_name='Tipo')),
                ('data', models.DateField()),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='images/user')),
                ('criancas', models.ManyToManyField(blank=True, to='home.crianca')),
                ('salas', models.ManyToManyField(blank=True, to='home.sala')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
